#include QMK_KEYBOARD_H
#include "bootmagic.h"
#include "version.h"
#define DVORAK 0
#define QWERTY 1
#define FN 2

enum custom_keycodes
{
    COPY = SAFE_RANGE, // can always be here
    PASTE
};
bool CAPS_LED = false;

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ergodox(
        KC_AMPR, KC_LBRC, KC_LCBR, KC_RCBR, KC_LPRN, KC_EQL, KC_CIRC, KC_TAB,
        KC_Q, KC_P, KC_Y, KC_C, KC_B, KC_GRV, KC_LALT, LGUI_T(KC_A),
        LALT_T(KC_N), LSFT_T(KC_I), LCTL_T(KC_S), KC_F, KC_LSFT, KC_COMM,
        KC_DOT, KC_J, KC_G, KC_SCLN, TO(1), KC_LCTL, KC_HOME, KC_END, KC_PGUP,
        KC_PGDN, COPY, PASTE, LT(1, KC_ESC), KC_E, KC_BSPC,
        KC_TAB, // right hand
        KC_DLR, KC_ASTR, KC_RPRN, KC_PLUS, KC_RBRC, KC_EXLM, KC_HASH, KC_EQL,
        KC_V, KC_M, KC_U, KC_Z, KC_L, KC_SLSH, KC_D, RCTL_T(KC_T), RSFT_T(KC_H),
        RALT_T(KC_O), RGUI_T(KC_R), KC_MINS, TO(2), KC_SLSH, KC_W, KC_K,
        KC_MINS, KC_X, KC_BSLS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_F12, KC_H,
        KC_L, KC_K, LT(3,KC_J), LT(2, KC_ENT), KC_SPC),
    [1] = LAYOUT_ergodox(
        KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_MINS, KC_TRNS, KC_AMPR, KC_COMM,
        KC_DOT, KC_GRV, KC_CIRC, KC_TRNS, KC_TRNS, KC_LBRC, KC_LCBR,
        KC_RCBR, KC_LPRN, KC_EQL, KC_TRNS, KC_QUOTE, KC_NO, KC_NO, KC_NO, KC_NO,
        TO(0), RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_MOD, KC_TRNS,
        KC_TRNS, KC_NO, KC_LSFT, KC_TRNS, KC_EQL, KC_6, KC_7, KC_8, KC_9, KC_0,
        KC_GRV, KC_TRNS, KC_DLR, KC_SLSH, KC_MINS, KC_BSLS, KC_HASH, KC_BSLS,
        KC_ASTR, KC_RPRN, KC_PLUS, KC_RBRC, KC_EXLM, KC_MINS, KC_TRNS, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGDN,
        RGB_TOG, RGB_M_P, KC_TRNS, KC_TRNS, KC_BSPC, KC_ENT),
    [2] = LAYOUT_ergodox(
        KC_PERC, KC_P7, KC_P5, KC_P3, KC_P1, KC_P9, KC_CIRC, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_AT, KC_LGUI, KC_LALT,
        KC_LSFT, KC_LCTL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TILD, KC_P0, KC_2, KC_4,
        KC_P6, KC_P8, KC_TRNS, KC_TRNS, KC_TRNS, KC_P7, KC_P8, KC_P9, KC_PMNS,
        KC_TRNS, KC_TRNS, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_PSLS, KC_TRNS,
        KC_TRNS, KC_P1, KC_P2, KC_P3, KC_PENT, KC_ASTR, KC_P0, KC_P0, KC_PDOT,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [3] = LAYOUT_ergodox(
        KC_NO, KC_NO, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_F7,
        KC_F8, KC_F9, KC_NO, KC_NO, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_NO,
        KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_K, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_H, KC_J, KC_L, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)};
bool process_record_user(uint16_t keycode, keyrecord_t *record)
{
    switch (keycode)
    {
    case COPY:
        if (record->event.pressed)
        {
            register_code(KC_LGUI);
            register_code(KC_C);
            unregister_code(KC_LGUI);
            unregister_code(KC_C);
        }
        break;
    case PASTE:
        if (record->event.pressed)
        {
            register_code(KC_LGUI);
            register_code(KC_V);
            unregister_code(KC_LGUI);
            unregister_code(KC_V);
        }
    }
    return true;
};
// Set LED according to the default layer
void default_layer_led_set(void)
{
    switch (biton32(eeconfig_read_default_layer()))
    {
    case DVORAK:
        // LED2 for COLEMAK
        ergodox_right_led_1_on();
        break;
    };
};
void suspend_wakeup_init_user(void)
{
    default_layer_led_set();
};
layer_state_t layer_state_set_user(layer_state_t state)
{
    ergodox_led_all_off();
    switch (biton32(state))
    {
    case DVORAK:
        // LED2 for COLEMAK
        ergodox_right_led_1_on();
        break;
    case FN:
        // Red led on Pro Micro for Fn layer
        ergodox_right_led_3_on();
        break;
    case QWERTY:
        // LED3 for QWERTY
        ergodox_right_led_2_on();
        break;
    };

    if (CAPS_LED)
    {
        ergodox_right_led_2_on();
    }

    /*default_layer_led_set();*/

    return state;
}
